# SPDX-FileCopyrightText: 2025 Koen van Greevenbroek
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Plot global water availability, natural use, and slack (Mm³)."""

import logging
from pathlib import Path

import matplotlib
import pandas as pd
import pypsa

matplotlib.use("pdf")
import matplotlib.pyplot as plt

logger = logging.getLogger(__name__)

# Enable new PyPSA components API
pypsa.options.api.new_components_api = True


def _compute_water_balance(network: pypsa.Network) -> pd.DataFrame:
    """Return a one-row DataFrame with available, natural supply, slack, total use (Mm³)."""

    # Available: total water storage capacity (Mm³)
    available = 0.0
    # Natural supply: water actually drawn from stores (Mm³)
    natural_supply = 0.0
    stores = network.stores.static
    if not stores.empty and "carrier" in stores.columns:
        water_stores = stores[stores["carrier"] == "water"]
        if not water_stores.empty:
            available = float(water_stores.get("e_nom", pd.Series([0.0])).sum())

            p_store_df = network.stores.dynamic.p
            if not p_store_df.empty:
                p_store = p_store_df.loc[
                    :, water_stores.index.intersection(p_store_df.columns)
                ]
                natural_supply = float(p_store.clip(lower=0.0).sum().sum())

    # Slack water generated by slack generators (Mm3)
    slack = 0.0
    gens = network.generators.static
    if not gens.empty and "carrier" in gens.columns:
        water_slack_gens = gens[gens["carrier"] == "water_slack"]
        if not water_slack_gens.empty:
            p_gen_df = network.generators.dynamic.p
            if not p_gen_df.empty:
                dispatch = p_gen_df.loc[
                    :, water_slack_gens.index.intersection(p_gen_df.columns)
                ]
                slack = float(dispatch.clip(lower=0.0).sum().sum())

    total_use = natural_supply + slack

    df = pd.DataFrame(
        {
            "available_mm3": available,
            "natural_supply_mm3": natural_supply,
            "slack_mm3": slack,
            "total_use_mm3": total_use,
        },
        index=["global"],
    )
    return df


def _plot(df: pd.DataFrame, output_pdf: Path) -> None:
    plt.figure(figsize=(6, 4))
    ax = plt.gca()

    metrics = ["available_mm3", "natural_supply_mm3", "slack_mm3", "total_use_mm3"]
    labels = ["Available", "Natural supply", "Slack", "Total use"]
    values = [df.iloc[0][m] for m in metrics]

    bars = ax.bar(
        labels,
        values,
        color=["#66c2a5", "#fc8d62", "#8da0cb", "#1f78b4"],
        edgecolor="black",
    )
    ax.set_ylabel("Mm³")
    ax.set_title("Global water balance (annual)")
    ax.grid(axis="y", alpha=0.3)

    for bar, val in zip(bars, values, strict=False):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            val,
            f"{val:,.0f}",
            ha="center",
            va="bottom",
        )

    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_pdf, bbox_inches="tight", dpi=300)
    plt.close()
    logger.info("Wrote water balance plot to %s", output_pdf)


def _write_csv(df: pd.DataFrame, output_csv: Path) -> None:
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_csv, float_format="%.6g")
    logger.info("Wrote water balance table to %s", output_csv)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    logger.info("Loading solved network from %s", snakemake.input.network)
    network = pypsa.Network(snakemake.input.network)

    df = _compute_water_balance(network)
    _plot(df, Path(snakemake.output.pdf))
    _write_csv(df, Path(snakemake.output.csv))
